### PR TITLE
ITM-511: updates through integrated DRE ADM Server release

### PR DESCRIPTION
**Pull request by nextcen-dgemoets**
- Update `api.yaml` and `sample.yaml` to the latest swagger YAML from the evaluation server.
- Always allow `CHECK_ALL_VITALS`, regardless of presence of Pulse Ox.
- Validate that `transtions.actions` contains only valid `action_id`s from the scene.
- For “justify” `MESSAGE` actions, `relevant_state` is required.
- Open all files with utf-8 encoding.
- Warn if `MOVE_TO` is specified without a `character_id`.
- Change "required" to "recommended" in the places where we only warn.
- Don't flag *intent* to do things to unseen characters.

To test, validate `sample.yaml` file (make sure it validates), then make changes to it that should be flagged by the above changes:
- `python validator.py -f sample.yaml`

You'll need to be in the validator virtual environment; see the `README`.

### CODE REVIEW

**Comment by dereknop** [comment]
"Always allow CHECK_ALL_VITALS, regardless of presence of Pulse Ox"

Is this change because the server allows it but just won't return the associated data that pulse ox provides?

**Review by dereknop — APPROVED** [review]
I'm getting all of the proper warnings/errors when trying to go against the rules you described

**Comment by nextcen-dgemoets** [comment]
Whoops @dereknop -- I accidentally updated your comment instead of responding to it!

**Comment by Anchita14** [comment]
I tested the different rules and it looks good to me!

**Review by Anchita14 — APPROVED** [review]

**Pull request merged**
