### PR TITLE
updated injuries/locations to match sim

### PR DESCRIPTION
**Pull request by kaitlyn-sharo**
- Fix burn locations (I think we might have added extras because we have full body and left/right body and we decided they could kind of piece it together themselves, but I decided to keep left side and right side to cover that, since there is no "side" burn)
- Make abrasion = laceration and make sure it matches the sim (I wish we would just take abrasion away)
- Allow any combination of injury/location in training mode (this will also apply to the military branch checks)
- Cleaned up erroneously committed test files

To test:
Play around with different injuries in the test.yaml file, with and without training mode on

### CODE REVIEW

**Review by nextcen-dgemoets — COMMENTED** [review]
I like what you did with adding `unspecified` to `Laceration`.  Maybe we should do that will all injuries?  Basically, we're letting scenario designers say it doesn't matter where the injury is, and we can choose what we want in the sim.

I'm confused about `Abrasion`.  What is it in the sim and why is it identical to laceration?  The only abrasion I know about is the "forehead scrape" which takes a pressure bandage.

I think I'm okay with allowing any combination of injury/location in training mode, and I think I know why you're applying it to the military branch checks, but I think we should check with @brianpippin .  The reason we have those checks is so that there's nothing embarrassing (e.g., a DARPA program not knowing what a Navy O-3 is).  I'm not sure we can waive that for text-based scenarios.

**Comment by kaitlyn-sharo** [comment]
> I like what you did with adding `unspecified` to `Laceration`. Maybe we should do that will all injuries? Basically, we're letting scenario designers say it doesn't matter where the injury is, and we can choose what we want in the sim.

Done!


> I'm confused about `Abrasion`. What is it in the sim and why is it identical to laceration? The only abrasion I know about is the "forehead scrape" which takes a pressure bandage.

We've discussed this before. I was told that Abrasion was the same as laceration (but maybe a little more extreme?) which is what I was messaging you about this morning. I don't think abrasion is necessary at all. Forehead scrape can easily be defined as a forehead laceration, in my opinion.


> I think I'm okay with allowing any combination of injury/location in training mode, and I think I know why you're applying it to the military branch checks, but I think we should check with @brianpippin . The reason we have those checks is so that there's nothing embarrassing (e.g., a DARPA program not knowing what a Navy O-3 is). I'm not sure we can waive that for text-based scenarios.

**Comment by nextcen-dgemoets** [comment]
> We've discussed this before. I was told that Abrasion was the same as laceration (but maybe a little more extreme?) which is what I was messaging you about this morning. I don't think abrasion is necessary at all. Forehead scrape can easily be defined as a forehead laceration, in my opinion.

I'm sorry-- I didn't circle back to that text from this early morning.  I don't see a problem with removing Abrasion entirely from the API, and if the YAML calls for a forehead laceration, we add a "forehead scrape" in the sim.  Maybe we should double-check with @brianpippin  first, though?  I'll just need to remember to remove it from the swagger and the server.  No MRE scenarios use Abrasion (shocking).

**Review by nextcen-dgemoets — APPROVED** [review]

**Review by brianpippin — APPROVED** [review]
LGTM

**Pull request merged**
