### PR TITLE
ITM-206: Update for changes through 05-Feb

### PR DESCRIPTION
**Pull request by nextcen-dgemoets**
[Co-authored by @kaitlyn-sharo ]

* Add `characterMatching` and `unique` rule types
* Change `aid_delay` to a list and require an `id`
* Validate that `next_scene` is a valid id in the list of `scenes`
* Add  `Injury.source_character`, which must be a valid `character_id` in the scene (or state)
* Make `characters` required in `scenes[].state`
* Make `state` required in `scenes[1+]`
* Add requirement for `parameters.evac_id` to `MOVE_TO_EVAC` action mapping
* Various other changes to the YAML that simply require re-generation.

### CODE REVIEW

**Review by kaitlyn-sharo — APPROVED** [review]

**Comment by nextcen-dgemoets** [comment]
@kaitlyn-sharo   There seems to be a regression with the `conditionalRequired` rule set.  Things like requiring a `character_id` or `parameters` on certain actions isn't getting flagged.  Could you investigate when you have available ITM hours?

**Comment by nextcen-dgemoets** [comment]
Also, ideally I'd like a rule where at least one scene (including the 0th) must have `end_scene_allowed=true`.  It's a nice-to-have, not a requirement, though.

**Comment by kaitlyn-sharo** [comment]
> Also, ideally I'd like a rule where at least one scene (including the 0th) must have `end_scene_allowed=true`. It's a nice-to-have, not a requirement, though.

Added

**Review by kaitlyn-sharo — APPROVED** [review]

**Comment by dereknop** [comment]
I went through each of the rules listed in the pr and tried to break them, all of the rules seem to be properly enforced.

**Review by dereknop — APPROVED** [review]

**Review by brianpippin — APPROVED** [review]
Looks good!

**Pull request merged**
